apiVersion: exoscale.crossplane.io/v1
kind: IAMKey
metadata:
  name: iam-key-local-dev
spec:
  forProvider:
    keyName: iam-key-local-dev
    services:
      sos:
        buckets:
          - bucket-local-dev
    zone: CH-DK-2
  providerConfigRef:
    name: provider-config
  writeConnectionSecretToRef:
    name: my-exoscale-user-credentials
    namespace: default
