site:
  title: Exoscale Provider for Crossplane
  start_page: provider-exoscale::index.adoc
  url: https://vshn.github.io/provider-exoscale
content:
  sources:
    - url: ../antora
      branches:
        - HEAD
        - docs/v*
      start_path: docs
ui:
  bundle:
    url: https://github.com/vshn/antora-ui-default/releases/download/2.0.15/ui-bundle.zip
    snapshot: true
output:
  dir: .public/
  clean: true
